version: 2

project_name: atest-ext-ai

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: atest-ext-ai
    main: ./cmd/atest-ext-ai
    binary: atest-ext-ai
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.gitCommit={{.FullCommit}}
      - -X main.buildDate={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: default
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: 'SHA256SUMS'
  algorithm: sha256

release:
  draft: false
  prerelease: auto
  mode: replace
  name_template: "Release {{.Tag}}"
  header: |
    ## Release {{.Tag}}

    This release includes cross-platform binaries for atest-ext-ai.
  footer: |
    **Full Changelog**: https://github.com/{{ .Env.GITHUB_REPOSITORY || "owner/repo" }}/compare/{{.PreviousTag}}...{{.Tag}}

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^style:'
      - '^refactor:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: 'Security Updates'
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 2
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\(.+\))??!?:.+$'
      order: 3
    - title: 'Other Changes'
      order: 999

